### ISSUE TITLE
The plugin stopped working in QGIS 4.2

### ISSUE THREAD

**Issue by kerkovits** [florianneukirchen/scipy_filters#10]
Since QGIS 4.2.2 (Linux), the plugin does not start.

I only get the following, not so useful error:

```
File "/home/****/.local/share/QGIS/QGIS4/profiles/default/python/plugins/scipy_filters/ui/scipy_processing_dialog.py", line 1, in <module>
from qgis.gui import (
...<6 lines>...
)
ImportError: cannot import name 'QgsProcessingAlgorithmDialogBase' from 'qgis.gui' (/usr/lib64/python3.14/site-packages/qgis/gui/__init__.py)
```

I cannot tell if it is a bug in QGIS, or this plugin.

**Comment by florianneukirchen** [comment]
Thanks for reporting. This is a terrible API breakage by QGIS. The old WidgetWrapper was deprecated before 4.0 without providing a new API. Back then I worked weeks to subclass this base class to get the plugin working for 4.0, and now they removed the base class and provide a new class QgsAbstractProcessingParameterWidgetWrapper. Unfortunately, this requires a major rewrite of the code base and at the moment I don't have the time for that.

**Comment by florianneukirchen** [comment]
Fixed in git. Root cause: QGIS 4.2 removed QgsProcessingAlgorithmDialogBase entirely, which this plugin's custom processing dialog subclassed — hence the ImportError.

Fixed in upcoming version 2.3 (main branch), which targets QGIS ≥ 4.2 and ports the dialog to QgsProcessingAlgorithmWidgetBase, the replacement class. If you're on QGIS 3.x (or 4.0/4.1), use version 2.2 instead, from the [qgis3 branch](https://github.com/florianneukirchen/scipy_filters/tree/qgis3) — main no longer supports QGIS < 4.2.

This plugin still builds its own processing dialog by hand instead of using QGIS's modern per-parameter widget registration (QgsAbstractProcessingParameterWidgetWrapper / QgsProcessingParameterWidgetFactoryInterface): that's blocked by [an upstream QGIS bug](https://github.com/qgis/QGIS/issues/67401) — pure-Python subclasses of QgsAbstractProcessingParameterWidgetWrapper silently fail to render when obtained through QgsProcessingGuiRegistry (SIP type-erasure on the C++ boundary).
